# Generated by Django 5.0 on 2024-04-19 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_qualities_person_alter_skill_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.person'),
        ),
        migrations.AlterField(
            model_name='qualities',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualities', to='api.person'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='api.person'),
        ),
    ]
